spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 200KB
      max-file-size: 200KB
      max-request-size: 200KB

application:
  bucket:
    name: muluadams3bucket

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: us-east-2
    stack:
      auto: false

